// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID       string `json:"id"`
	Task     string `json:"task"`
	Internal string `json:"internal"`
	User     string `json:"user"`
	Branch   string `json:"branch"`
	Status   string `json:"status"`
	Db       bool   `json:"db"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
