package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"ctasks/graph/model"
	"fmt"
)

// DelUser is the resolver for the delUser field.
func (r *mutationResolver) DelUser(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: DelUser - delUser"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, status *string) ([]*model.Task, error) {
	return []*model.Task{
		{
			ID:       "201",
			Task:     "t-01",
			Internal: "YLUQ-801",
			Status:   "已完成",
		},
		{
			ID:       "305",
			Task:     "t-12",
			Internal: "YLUQ-1001",
			Status:   "待处理",
		},
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return &model.User{ID: "1001", Name: "Nia"}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
